# Generated by Django 5.0.6 on 2024-06-12 08:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeId', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='REG_DT', verbose_name='생성일')),
                ('chg_dt', models.DateTimeField(auto_now=True, db_column='CHG_DT', verbose_name='수정일')),
                ('name', models.CharField(db_column='NAME', max_length=255, verbose_name='이름')),
                ('sub_name', models.CharField(db_column='SUB_NAME', max_length=255, null=True, verbose_name='서술용 이름')),
                ('sub_display_name', models.CharField(db_column='SUB_DISPLAY-NAME', max_length=255, null=True, verbose_name='화면용 이름')),
                ('dictionary', models.CharField(db_column='DICTIONARY', max_length=255, null=True, verbose_name='설명')),
                ('enumerations', models.JSONField(db_column='ENMERATIONS', default=dict)),
                ('enumerations_html', models.CharField(blank=True, db_column='ENUMERATIONS_HTML', default='', max_length=255, null=True, verbose_name='속성값 목록 HTML')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_column='PARENT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='schema.node', verbose_name='상위분류')),
            ],
            options={
                'db_table': 'NODE',
                'ordering': ['nodeId'],
            },
        ),
    ]
