# Generated by Django 5.0.6 on 2024-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='enumerations',
            field=models.JSONField(db_column='ENUMERATIONS', default=dict),
        ),
    ]
