# Generated by Django 5.0.6 on 2024-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='enumerations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='node',
            name='enumerations_html',
            field=models.CharField(blank=True, db_column='ENUMERATIONS_HTML', max_length=255, null=True, verbose_name='속성값 목록 HTML'),
        ),
        migrations.DeleteModel(
            name='LeafNode',
        ),
    ]
