# Generated by Django 5.0.6 on 2024-06-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_alter_node_enumerations_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='node',
            name='nodeId',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
