# Generated by Django 5.0.6 on 2024-06-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_alter_node_options_alter_node_nodeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['nodeId']},
        ),
    ]
