# Generated by Django 5.0.6 on 2024-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_alter_node_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='enumerations',
            field=models.JSONField(db_column='ENMERATIONS', default=dict),
        ),
    ]
